-- WhatsApp Attendance preparation
-- Add a WhatsApp number to each employee record in the existing employees JSON.
-- Recommended field name: whatsapp_phone
--
-- Example employee object:
-- {"id":"...","empId":"EMP001","name":"Employee Name","whatsapp_phone":"9876543210"}
--
-- No new attendance table is required by this bridge.
-- It writes to the existing khata_data row where key='timelog'.
-- Your current web app already uses Time Log as the attendance source.
